### PR TITLE
Auto-detect the user's locale

### PR DESCRIPTION
**Pull request by markrickert**
...and output km/mi based on their phone's country settings on the markers.

### CODE REVIEW

**Comment by a1phanumeric** [comment]
Dude, props for keeping to the coding style.

I will refactor the whole project soon - it needs it. Our style of variable naming will remain though.

**Comment by markrickert** [comment]
Thanks! Everything look OK? My users in the US will want to see things in _stupid_ imperial units, not metric. Damn, i wish the entire world was on the metric system... but I can only wish!

**Comment by markrickert** [comment]
As far as refactoring goes, I'm more partial to using synthesized getters/setters that you can override instead of named methods that set instance variables. That's kind of what I did with the `showsCloseButton` feature.

**Comment by a1phanumeric** [comment]
Yep all looks good and works well :) thanks!

Refactoring: It's just something I love doing. I'm happy to make the use of synthesized getters/setters as long as we use the following format

`@synthesize myVar = _myVar`

I just prefer using _<VAR> for local references. What do you think?

**Comment by markrickert** [comment]
I agree, but the new version of the compiler does that for us _automatically_ (as you can see in this commit). :smiley: 
1. I did: `@property (nonatomic) BOOL usesMetric;`
2. Then the synthesize is done for us automatically by ARC.
3. I referenced the local iVar `_usesMetric` in the initialization method and set it to yes or no.

**Comment by a1phanumeric** [comment]
I need to update Xcode... I normally (believe it or not) use TextMate for iOS, just Xcode for compiling!

**Pull request merged**
